routes/web.php
<?php

Auth::routes();
/*
 |--------------------------------------------------------
 |                Home Controller Routes
 |--------------------------------------------------------
 */
Route::get('/', 'HomeController@index')->name('home');

/*
 |--------------------------------------------------------
 |                Thread Controller Routes
 |--------------------------------------------------------
 */
Route::get('threads', 'ThreadController@index')->name('threads');
Route::get('threads/create', 'ThreadController@create')->name('threads.create');

Route::post('threads/{analysisId}', 'ThreadController@store')->name('threads.store')->middleware('must-be-confirmed');
Route::get('threads/{channel}', 'ThreadController@index');
Route::get('threads/{channel}/{thread}', 'ThreadController@show');
Route::patch('threads/{channel}/{thread}', 'ThreadController@update');
Route::delete('threads/{channel}/{thread}', 'ThreadController@destroy');
/*
 |--------------------------------------------------------
 |                Replies Controller Routes
 |--------------------------------------------------------
 */
Route::delete('/replies/{reply}', 'RepliesController@destroy')->name('replies.destroy');
Route::patch('/replies/{reply}', 'RepliesController@update');
Route::get('/threads/{channel}/{thread}/replies', 'RepliesController@index');
Route::post('/threads/{channel}/{thread}/replies', 'RepliesController@store');
/*
 |--------------------------------------------------------
 |               Best Replies Controller Routes
 |--------------------------------------------------------
 */
Route::post('/replies/{reply}/best', 'BestRepliesController@store')->name('best-replies.store');
/*
 |--------------------------------------------------------
 |                Favorites Controller Routes
 |--------------------------------------------------------
 */
Route::post('/replies/{reply}/favorites', 'FavoritesController@store');
Route::delete('/replies/{reply}/favorites', 'FavoritesController@destroy');
/*
 |--------------------------------------------------------
 |                Profiles Controller Routes
 |--------------------------------------------------------
 */
Route::get('/profiles/{user}', 'ProfilesController@show')->name('profile');
/*
 |--------------------------------------------------------
 |           UserNotifications Controller Routes
 |--------------------------------------------------------
 */
Route::delete('/profiles/{user}/notifications/{notification}', 'UserNotificationsController@destroy');
Route::get('/profiles/{user}/notifications', 'UserNotificationsController@index');
/*
 |--------------------------------------------------------
 |          ThreadSubscriptions Controller Routes
 |--------------------------------------------------------
 */
Route::post('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@store')->middleware('auth');
Route::delete('/threads/{channel}/{thread}/subscriptions', 'ThreadSubscriptionsController@destroy')->middleware('auth');
/*
 |--------------------------------------------------------
 |            UsersController Controller Routes
 |--------------------------------------------------------
 */
Route::get('api/users', 'Api\UsersController@index');
/*
 |--------------------------------------------------------
 |         UsersAvatarController Controller Routes
 |--------------------------------------------------------
 */
Route::post('api/users/{user}/avatar', 'Api\UsersAvatarController@store')->middleware('auth')->name('avatar');
/*
 |--------------------------------------------------------
 |            RegistrationConfirm Controller
 |--------------------------------------------------------
 */
Route::get('/register/confirm', 'Auth\RegisterConfirmationController@index')->name('register.confirm');
/*
 |--------------------------------------------------------
 |           LockedThreadsController Controller
 |--------------------------------------------------------
 */
Route::post('/lock-threads/{thread}', 'LockedThreadsController@store')->name('locked-threads.store')->middleware('admin');
Route::delete('/lock-threads/{thread}', 'LockedThreadsController@destroy')->name('locked-threads.destroy')->middleware('admin');
/*
 |--------------------------------------------------------
 |             SearchController Controller
 |--------------------------------------------------------
 */
Route::get('threads/search', 'SearchController@show');
/*
 |--------------------------------------------------------
 |               Chart Controller Routes
 |--------------------------------------------------------
 */
Route::get('analysis/chart', 'AnalysisController@index')->name('analysis.index');
Route::post('analysis/chart', 'AnalysisController@store')->name('analysis.store')->middleware('auth');
/*
 |--------------------------------------------------------
 |               Threads Comments Routes
 |--------------------------------------------------------
 */
Route::post('analysis/{thread}/comment', 'ThreadsCommentsController@store')->name('threads.comments.store')->middleware('auth');
Route::get('analysis/{thread}/comments', 'ThreadsCommentsController@index')->name('threads.comments.index');
Route::get('threads/{channel}/{thread}/attach', 'ThreadsCommentsController@show')->name('threads.comment.show')->middleware('auth');
/*
 |--------------------------------------------------------
 |            Thread Favorites Controller Routes
 |--------------------------------------------------------
 */
Route::post('api/threads/{thread}/favorites', 'Api\ThreadFavoritesController@store');
Route::delete('api/threads/{thread}/favorites', 'Api\ThreadFavoritesController@destroy');

/*
 |--------------------------------------------------------
 |               Administrators Routes
 |--------------------------------------------------------
 */
Route::group([
    'prefix' => 'admin',
    'middleware' => 'admin',
    'namespace' => 'Admin',
], function () {
    Route::get('', 'DashboardController@index')->name('admin.dashboard.index');
//    Route::post('channels', 'ChannelsController@store')->name('admin.channels.store');
//    Route::get('channels', 'ChannelsController@index')->name('admin.channels.index');
//    Route::get('channels/create', 'ChannelsController@create')->name('admin.channels.create');
});

app/Analysis.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Analysis extends Model
{
    protected $guarded = [];

    protected $casts = ['analysis_data' => 'json'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function thread()
    {
        return $this->hasOne(Thread::class, 'analysis_id');
    }

    /**
     * @return mixed
     */
    public static function addAnalysis()
    {
        return static::create([
            'user_id' => auth()->id(),
            'image_url' => \request('image_url'),
            'analysis_data' => \request('analysis_data'),
        ]);
    }

    /**
     * @param $analysisId
     * @return mixed
     */
    public static function isValidAnalysis($analysisId)
    {
        return self::where('user_id', auth()->id())->where('published', false)->where('id', $analysisId)->first();
    }

    /**
     * @return string
     */
    public function getImageFullPathAttribute()
    {
        return "https://www.tradingview.com/x/" . $this->image_url;
    }

}

resources/views/_analysis.blade.php
@if($thread)
    <div class="tile is-parent">
        <article class="tile is-child box">
            <p class="is-size-5 has-text-grey">آخرین تحلیل ارسالی</p>
            <hr class="hr-bold">
            <div class="card-content">
                <div class="media">
                    <div class="media-content is-clipped">
                        <div class="is-pulled-right">
                            <p class="is-size-6">
                                <a href="{{route('profile',$thread->owner)}}">{{$thread->owner->name}}</a>
                            </p>
                            <p class="is-size-7 is-pulled-right">{{$thread->owner->name}}@</p>
                        </div>
                        <div class="is-pulled-left">
                            <p class="is-size-7 is-hidden-mobile">{{$thread->channel->name}}</p>
                        </div>
                    </div>
                    <div class="media-right is-paddingless">
                        <figure class="image is-48x48">
                            <img src="{{$thread->owner->avatar_path}}"
                                 alt="{{$thread->owner->name}}">
                        </figure>
                    </div>
                </div>
            </div>
            <div class="card-image">
                <figure class="image is-3by2">
                    <img src="{{$thread->analysis->image_full_path}}"
                         alt="Placeholder image">
                </figure>
            </div>
            <div class="card-content">
                <div class="columns">
                    <div class="column is-paddingless">
                        <div class="is-inline-flex is-black">
                            <div class="tags has-addons">
                                    <span class="tag is-light">
                                        <span class="icon has-text-black">
                                            <i class="fas fa-eye"></i>
                                        </span>
                                    </span>
                                <span class="tag is-info">
                                        {{$thread->visits()->count()}}
                                    </span>
                            </div>
                            <div class="tags has-addons mg-r-5">
                                    <span class="tag is-light">
                                        <span class="icon has-text-black">
                                            <i class="far fa-comment"></i>
                                        </span>
                                    </span>
                                <span class="tag is-info">
                                        {{$thread->replies_count}}
                                    </span>
                            </div>
                            <div class="is-clearfix"></div>
                        </div>
                        <div class="is-pulled-left has-icon has-text-info">
                            <p class="is-size-7">
                                {{$thread->created_at->diffForHumans()}}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="columns">
                    <div class="column is-paddingless">
                        <a href="{{$thread->path()}}">
                            @if(auth()->check() && $thread->hasUpdatesFor(auth()->user()))
                                <strong>
                                    {{str_limit($thread->title,30)}}
                                </strong>
                            @else
                                {{str_limit($thread->title,30)}}
                            @endif
                        </a>
                    </div>
                </div>
            </div>
        </article>
    </div>
@endif

resources/views/_tile.blade.php
<div class="tile is-ancestor">
    @if(count($popularThreads))
        <div class="tile is-vertical">
            <div class="tile">
                <div class="tile is-parent is-vertical">
                    @foreach($popularThreads as $thread)
                        <article class="tile is-child box">
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-content is-clipped">
                                        <div class="is-pulled-right">
                                            <p class="is-size-6">
                                                <a href="{{route('profile',$thread->owner)}}">{{$thread->owner->name}}</a>
                                            </p>
                                            <p class="is-size-7 is-pulled-right">{{$thread->owner->name}}@</p>
                                        </div>
                                        <div class="is-pulled-left">
                                            <span class="tag is-warning">پر بازدید</span>
                                        </div>
                                    </div>
                                    <div class="media-right is-paddingless">
                                        <figure class="image is-48x48">
                                            <img src="{{$thread->owner->avatar_path}}"
                                                 alt="{{$thread->owner->name}}">
                                        </figure>
                                    </div>
                                </div>
                            </div>
                            <div class="card-image">
                                <figure class="image is-2by1">
                                    <img src="{{$thread->analysis->image_full_path}}"
                                         alt="Placeholder image">
                                </figure>
                            </div>
                            <div class="card-content">
                                <div class="columns">
                                    <div class="column is-paddingless">
                                        <div class="is-inline-flex is-black">
                                            <div class="tags has-addons">
                                    <span class="tag is-light">
                                        <span class="icon has-text-black">
                                            <i class="fas fa-eye"></i>
                                        </span>
                                    </span>
                                                <span class="tag is-info">
                                        {{$thread->visits()->count()}}
                                    </span>
                                            </div>
                                            <div class="tags has-addons mg-r-5">
                                    <span class="tag is-light">
                                        <span class="icon has-text-black">
                                            <i class="far fa-comment"></i>
                                        </span>
                                    </span>
                                                <span class="tag is-info">
                                        {{$thread->replies_count}}
                                    </span>
                                            </div>
                                            <div class="is-clearfix"></div>
                                        </div>
                                        <div class="is-pulled-left has-icon has-text-info">
                                            <p class="is-size-7">
                                                {{$thread->created_at->diffForHumans()}}
                                            </p>
                                            <p class="is-size-7 is-hidden-mobile">{{$thread->channel->name}}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="columns">
                                    <div class="column is-paddingless">
                                        <a href="{{$thread->path()}}">
                                            @if(auth()->check() && $thread->hasUpdatesFor(auth()->user()))
                                                <strong>
                                                    {{str_limit($thread->title,30)}}
                                                </strong>
                                            @else
                                                {{str_limit($thread->title,30)}}
                                            @endif
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </article>
                    @endforeach
                </div>
            </div>
        </div>
    @endif
    <div class="tile is-8">
        <div class="tile">
            @include('_analysis')
        </div>
    </div>
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

    <section class="hero is-bold is-info">
        <div class="hero-body">
            <div class="container">
                <div class="columns">
                    <div class="column is-vertically-centered">
                        <div class="is-text-column">
                            <h1 class="title">
                                پودونک
                            </h1>
                            <h2 class="subtitle">
                                مجمع تحلیل و مبادله ارزهای دیجیتال
                            </h2>
                        </div>
                    </div>
                    <div class="column">
                        <figure class="image is-3by2">
                            <img src="{{asset('images/graph.svg')}}" alt="">
                        </figure>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <div class="section is-medium">
        <div class="container">
            <div class="columns">
                <div class="column">
                    <p class="title has-text-centered">همین حالا شروع کنید</p>
                    <div class="hero-buttons">
                        <a href="{{route('analysis.index')}}" class="button is-primary is-large">
                            ارسال تحلیل
                        </a>
                        <a href="{{route('threads')}}" class="button is-link is-large mr-1">
                            مشاهده تحلیل ها
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="section section-tile-landing">
        <div class="container">
            @include('_tile')
        </div>
    </div>


    <section class="hero is-info is-fullheight trading-section">
        <div class="hero-body">
            <div class="container">
                <div class="columns">
                    <div class="column">
                        <h1 class="title">
                            پلتفرم آموزشی مبادله ارز دیجیتال
                        </h1>
                        <h2 class="subtitle">
                            به راحتی و بدون هیچ هزینه ای شروع به یادگیری مبادله ارز دیجیتال کنید
                        </h2>
                    </div>
                    <div class="column has-text-centered">
                        <div class="content">
                            <p class="has-text-justified">
                                اگر شما تازه قصد ورود به بازار ارز دیجیتال دارید این جا بهترین جا برای شروع است. به دلیل
                                نوسان زیاد قیمت در بازار ارز دیجیتال در صورت تازه کار بودن ممکن است متحمل ضرر زیادی شوید
                                (دیدم که میگم!!! :) ) پس بهتر است قبل از ورود به بازار اصلی با استفاده از سامانه مبادله
                                ارز
                                دیجیتال پودونک که کاملا با پلتفرم های موجود یکسان است شروع به معامله کردن کنید و پس از
                                یادگیری و آشنا شدن وارد بازار اصلی شوید.
                            </p>
                            <a href="https://demo.podonak.com/" class="button is-large trading-btn">ورود به بازار</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>



    {{--<div class="section is-medium chart-section">--}}
    {{--<div class="container">--}}
    {{--<div class="columns">--}}
    {{--<div class="column has-text-centered box">--}}
    {{--<p class="title has-text-grey-dark">نمودار لحظه ای قیمت</p>--}}
    {{--</div>--}}
    {{--<div class="column has-text-centered">--}}
    {{--<a href="{{route('analysis.index')}}" class="button is-info is-large is-rounded">--}}
    {{--<i class="fas fa-chart-bar"></i>--}}
    {{--<span class="mr-1">--}}
    {{--مشاهده نمودار--}}
    {{--</span>--}}
    {{--</a>--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--</div>--}}

    <div class="section is-medium is-mobile has-text-centered">
        <div class="container">
            <div class="content">
                <p class="title has-text-grey-dark">
                    نرخ ارز پودونک از کجا تامین می شود؟
                </p>
                <p class="subtitle has-text-grey-dark">
                    در پودونک نرخ ها از اکسچنج های معتبر زیر تامین می شود.
                </p>
            </div>
            <div class="columns">
                <div class="column">
                    <figure class="image is-16by9">
                        <img src="{{asset('images/bifinex.svg')}}" alt="bitfinex">
                    </figure>
                </div>
                <div class="column is-hidden-mobile"></div>
                <div class="column">
                    <figure class="image is-16by9">
                        <img src="{{asset('images/binance.svg')}}" alt="binance">
                    </figure>
                </div>
            </div>
        </div>
    </div>

@endsection